apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yjd1sfgua-nodejs 
  janus-idp.io/tekton: yjd1sfgua-nodejs
  backstage.io/kubernetes-id: yjd1sfgua-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yjd1sfgua-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml