apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: yjd1sfgua-nodejs-gitops
  description: This is GitOps manifest for yjd1sfgua-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=yjd1sfgua-nodejs
    backstage.io/kubernetes-id: yjd1sfgua-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: yjd1sfgua-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:yjd1sfgua-nodejs
